services:
  mq:
    image: rabbitmq:3-management-alpine
    container_name: llm-twin-mq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: llm-twin-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
      - qdrant-data:/qdrant_data
    restart: always

  postgres:
    image: postgres:15
    container_name: llm-twin-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "8888:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/migrations:/migrations
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio:latest
    container_name: llm-twin-minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin # Change these in production!
      MINIO_ROOT_PASSWORD: minioadmin # Change these in production!
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  cdc-listener:
    container_name: llm-twin-cdc-listener
    build:
      context: .
      dockerfile: .docker/Dockerfile.cdc_listener
    env_file:
      - .env
    restart: always # Keep listener running
    depends_on:
      - postgres
      - mq

  api: # Added API service definition
    container_name: llm-twin-api
    build:
      context: .
      dockerfile: .docker/Dockerfile.api
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - mq
      - postgres
      - qdrant # API needs Qdrant for RAG retriever
    # Consider adding resource limits for production:
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 4G
    #     reservations:
    #       memory: 2G
    restart: always

  feature_pipeline:
    image: "llm-twin-feature-pipeline"
    container_name: llm-twin-feature-pipeline
    build:
      context: .
      dockerfile: .docker/Dockerfile.feature_pipeline
    environment:
      BYTEWAX_PYTHON_FILE_PATH: "src/feature_pipeline/main:flow"
      DEBUG: "false"
      BYTEWAX_KEEP_CONTAINER_ALIVE: "true"
    env_file:
      - .env
    depends_on:
      - mq
      - qdrant
    restart: always

volumes: #name the volumes that Docker will manage and persist data. volumes live outside of container life cycle. any writes in the container are directly ported and written to volumes
  qdrant-data:
  postgres-data:
  minio-data:
